### ISSUE TITLE
Error when running the app.

### ISSUE THREAD

**Issue by ThreeDeePrint** [iAhsanJaved/InstagramUsernameTaker#2]
Hi, changed the login details in the config file.
Try to run the main.py on 3.9 and 2.7, and in both instances i get the following error.

`Would you like to start (y/n)?: y
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\kalma\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\kalma\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kalma\Desktop\InstagramUsernameTaker-master\main.py", line 121, in checkUsername
    json_data = json.loads(res.text)
  File "C:\Users\kalma\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\kalma\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\kalma\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
PS C:\Users\kalma\Desktop\InstagramUsernameTaker-master>`

Any ideas why its not working ?

**Comment by ghost** [comment]
your config.json file has nothing in it
